// console.log(Swal.fire({ showAlerts[1].title, showAlerts[1].footer }));

export const showAlerts = {
  1: {
    title: "🍔 BBQ 🍔 ",
    imageUrl: "https://i.imgur.com/c8qugHI.jpg",
    imageWidth: 300,
    imageHeight: 230,
    imageAlt: "Custom image",
    footer: "Friday, September 1st",
  },
  // 2: { title: "Parmesan Chicken Cutlets", text: "w/ penne vodka", footer: "Wednesday, September 2nd" },
  // 3: { title: "Sandwich day", footer: "Thursday, August 3rd" },
  // 4: { title: "Blackened Chicken & Veggies", footer: "Friday, August 4th" },
  5: { title: "Cali Burger Bar", footer: "Tuesday, September 5th" },
  6: { title: "TBD", footer: "Wednesday, September 6th" },
  7: {
    title: "Grilled Salmon",
    text: "w/ sweet potatoes and salad",
    footer: "Thursday, September 7th",
  },
  8: { title: "TBD", footer: "Friday, September 8th" },
  11: { title: "TBD", footer: "Monday, September 11th" },
  12: { title: "TBD", footer: "Tuesday, September 12th" },
  13: { title: "TBD", footer: "Wednesday, September 13th" },
  14: { title: "TBD", footer: "Thursday, September 14th" },
  15: { title: "TBD", footer: "Friday, September 15th" },
  18: { title: "TBD", footer: "Monday, September 18th" },
  19: { title: "TBD", footer: "Tuesday, September 19th" },
  21: { title: "TBD", footer: "Wednesday, September 21st" },
  22: { title: "TBD", footer: "Friday, September 22nd" },
  25: { title: "TBD", footer: "Monday, September 25th" },
  26: { title: "TBD", footer: "Tuesday, September 26th" },
  27: { title: "TBD", footer: "Wednesday, September 27th" },
  28: { title: "TBD", footer: "Thursday, September 28th" },
  29: { title: "TBD", footer: "Friday, September 29th" },
  // 30: { title: "TBD", footer: "Friday, September 30th" },

  // 6: { title: "Sweetgreens", footer: "Thursday, September 6th" },
  // 7: { title: "Sweetgreens", footer: "Monday, September 7th" },
  // 8: {
  //   title: "Chicken Cutlets & Mashed Taters",
  //   text: "w/ corn and salad",
  //   footer: "Tuesday, September 8th",
  // },
  // 9: { title: "Paninis & salads", footer: "Wednesday, September 9th" },
  // 10: { title: "Baja Salad", footer: "Thursday, September 10th" },
  // 11: { title: "Chop't", footer: "Friday, September 11th" },
  // 14: { title: "Penne Vodka w/ Meatballs", footer: "Monday, September 14th" },
  // 15: { title: "Taco Bar", footer: "Tuesday, September 15th" },
  // 16: {
  //   title: "Chicken Taquitos",
  //   text: "w/ Rice",
  //   footer: "Wednesday, September 16th",
  // },
  // 17: { title: "Chicken Masala", footer: "Thursday, September 17th" },
  // 18: { title: "Jerk Chicken", footer: "Friday, September 18th" },
  // 19: { title: "Chicken Quesadillas", footer: "Wednesday, September 19th" },
  // 20: { title: "Bombay Hut", footer: "Thursday, September 20th" },
  // 21: { title: "Cape Cod Salad", footer: "Monday, September 21st" },
  // 22: { title: "Flank Steak Salad", footer: "Tuesday, September 22nd" },
  // 23: { title: "Chick-fil-a", footer: "Wednesday, September 23rd" },
  // 24: { title: "Bombay Hut", footer: "Thursday, September 24th" },
  // 25: { title: "DIY Salmon BLT", footer: "Friday, September 25rd" },
  // 26: { title: "Cornflake Chicken", footer: "Wednesday, September 26th" },
  // 27: { title: "Chicken Cordon Bleu w/ Rice", footer: "Thursday, September 27th" },
  // 28: { title: "Shrimp Scampi ", footer: "Monday, September 28th" },
  // 29: { title: "Sweetgreen", footer: "Tuesday, September 29th" },
  // 30: { title: "Chicken Cordon Bleu", footer: "Wednesday, September 30th" },
  // 31: { title: "Paninis & salads", footer: "Thurday, September 31st" },
  // 28: { title: "🍔 BBQ 🍔 ", imageUrl: '../images/blaze.logo.png',
  //   imageWidth: 400,
  //   imageHeight: 200,
  //   imageAlt: 'Custom image',footer: "Friday, September 28th" },
  // 1: { title: "BTG BBQ", footer: "Friday, September 1th" },
  // 5: { title: "It's the weekend"}
};
